

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author edgar
 */
public class deposito extends javax.swing.JFrame {

    /**
     * Creates new form deposito
     */
    public deposito() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese el monto a depositar");

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese la cuenta a depositar");

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setText("DEPOSITAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCuenta)
                    .addComponent(txtMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(56, 56, 56))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel2)
                    .addContainerGap(260, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(102, 102, 102))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jLabel2)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(this, "Esta seguro que desea hacer este deposito?");
        
        String textoCuenta=txtCuenta.getText();
        int textoMonto=Integer.parseInt(txtMonto.getText());
        
        if (i==0){ //Este if es para confirmar el deposito//
            if(ProyectoCajero.Sesion==1){
                int monto=ProyectoCajero.cli1.getMonto();
                if(monto>textoMonto){
                    ProyectoCajero.cli1.setMonto(monto-textoMonto);
                    if (textoCuenta.equals(ProyectoCajero.cli2.getIdentidad())){
                    ProyectoCajero.cli2.setMonto(ProyectoCajero.cli2.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli3.getIdentidad())){ 
                    ProyectoCajero.cli3.setMonto(ProyectoCajero.cli3.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli4.getIdentidad())){
                    ProyectoCajero.cli4.setMonto(ProyectoCajero.cli4.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli5.getIdentidad())){
                    ProyectoCajero.cli5.setMonto(ProyectoCajero.cli5.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                }
                if(monto<textoMonto){ 
                    JOptionPane.showMessageDialog(this, "Fondos Insuficientes");
                }

            }
            
            if(ProyectoCajero.Sesion==2){
                int monto=ProyectoCajero.cli2.getMonto();
                if(monto>textoMonto){
                    ProyectoCajero.cli2.setMonto(monto-textoMonto);
                    if (textoCuenta.equals(ProyectoCajero.cli1.getIdentidad())){
                    ProyectoCajero.cli1.setMonto(ProyectoCajero.cli1.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli3.getIdentidad())){ 
                    ProyectoCajero.cli3.setMonto(ProyectoCajero.cli3.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli4.getIdentidad())){
                    ProyectoCajero.cli4.setMonto(ProyectoCajero.cli4.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli5.getIdentidad())){
                    ProyectoCajero.cli5.setMonto(ProyectoCajero.cli5.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                }
               if(monto<textoMonto){ 
                    JOptionPane.showMessageDialog(this, "Fondos Insuficientes");
                }
            }
            
            if(ProyectoCajero.Sesion==3){
                int monto=ProyectoCajero.cli3.getMonto();
                if(monto>textoMonto){
                    ProyectoCajero.cli3.setMonto(monto-textoMonto);
                    if (textoCuenta.equals(ProyectoCajero.cli2.getIdentidad())){
                    ProyectoCajero.cli2.setMonto(ProyectoCajero.cli2.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli1.getIdentidad())){ 
                    ProyectoCajero.cli1.setMonto(ProyectoCajero.cli1.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli4.getIdentidad())){
                    ProyectoCajero.cli4.setMonto(ProyectoCajero.cli4.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli5.getIdentidad())){
                    ProyectoCajero.cli5.setMonto(ProyectoCajero.cli5.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                }
                if(monto<textoMonto){ 
                    JOptionPane.showMessageDialog(this, "Fondos Insuficientes");
                }
            }
            
            if(ProyectoCajero.Sesion==4){
                int monto=ProyectoCajero.cli4.getMonto();
                if(monto>textoMonto){
                    ProyectoCajero.cli4.setMonto(monto-textoMonto);
                    if (textoCuenta.equals(ProyectoCajero.cli2.getIdentidad())){
                    ProyectoCajero.cli2.setMonto(ProyectoCajero.cli2.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli3.getIdentidad())){ 
                    ProyectoCajero.cli3.setMonto(ProyectoCajero.cli3.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli1.getIdentidad())){
                    ProyectoCajero.cli1.setMonto(ProyectoCajero.cli1.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli5.getIdentidad())){
                    ProyectoCajero.cli5.setMonto(ProyectoCajero.cli5.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                }
                if(monto<textoMonto){ 
                    JOptionPane.showMessageDialog(this, "Fondos Insuficientes");
                }
            }
            
            if(ProyectoCajero.Sesion==5){
                int monto=ProyectoCajero.cli5.getMonto();
                if(monto>textoMonto){
                    ProyectoCajero.cli1.setMonto(monto-textoMonto);
                    if (textoCuenta.equals(ProyectoCajero.cli2.getIdentidad())){
                    ProyectoCajero.cli2.setMonto(ProyectoCajero.cli2.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli3.getIdentidad())){ 
                    ProyectoCajero.cli3.setMonto(ProyectoCajero.cli3.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli4.getIdentidad())){
                    ProyectoCajero.cli4.setMonto(ProyectoCajero.cli4.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                    if (textoCuenta.equals(ProyectoCajero.cli1.getIdentidad())){
                    ProyectoCajero.cli1.setMonto(ProyectoCajero.cli1.getMonto()+textoMonto);
                    JOptionPane.showMessageDialog(this, "Deposito Realizado Con Exito");
                    }
                }
                if(monto<textoMonto){ 
                    JOptionPane.showMessageDialog(this, "Fondos Insuficientes");
                }
            }
            
            
            
            MenuPrincipal newframe = new MenuPrincipal(); //Llamar a MenuPrincipal
            newframe.setVisible(true);//Linea que ya la abre
        
            this.dispose();//este metodo sirve para cerrar la otra ventana 
        
        //pueden copiar y pegar si quieren//
        }
        if (i==2){//este if es para cuando se elije no
            MenuPrincipal newframe = new MenuPrincipal(); //Llamar a MenuPrincipal
            newframe.setVisible(true);//Linea que ya la abre
        
            this.dispose();//este metodo sirve para cerrar la otra ventana 
        
        //pueden copiar y pegar si quieren//
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        MenuPrincipal newframe = new MenuPrincipal(); //Llamar a MenuPrincipal
        newframe.setVisible(true);//Linea que ya la abre
        
        this.dispose();//este metodo sirve para cerrar la otra ventana 
        
        //pueden copiar y pegar si quieren solo cambien el nombre de los JFrame//
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
