
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author edgar
 */
public class Retiro extends javax.swing.JFrame {

    /**
     * Creates new form Retiro
     */
    public Retiro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Indique el monto a retirar: ");

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton1)
                        .addGap(82, 82, 82)
                        .addComponent(jButton2)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Esta seguro que desea hacer este Retiro?");

        if (i==0){ //Este if es para confirmar el deposito//
            
            int textoRetiro=Integer.parseInt(txtMonto.getText());
            
            if(ProyectoCajero.Sesion==1){
                
                int monto=ProyectoCajero.cli1.getMonto();
                if(monto>textoRetiro){
                ProyectoCajero.cli1.setMonto(monto-textoRetiro);
                JOptionPane.showMessageDialog(this, "Retiro Realizado Con Exito");
                }
                if(monto<textoRetiro){
                    JOptionPane.showMessageDialog(this, "Fondos Insuficientes");
                }
            }
            if(ProyectoCajero.Sesion==2){
                int monto=ProyectoCajero.cli2.getMonto();
                if(monto>textoRetiro){
                ProyectoCajero.cli2.setMonto(monto-textoRetiro);
                JOptionPane.showMessageDialog(this, "Retiro Realizado Con Exito");
                }
                if(monto<textoRetiro){
                    JOptionPane.showMessageDialog(this, "Fondos Insuficientes");
                }
            }
            if(ProyectoCajero.Sesion==3){
                int monto=ProyectoCajero.cli3.getMonto();
                if(monto>textoRetiro){
                ProyectoCajero.cli3.setMonto(monto-textoRetiro);
                JOptionPane.showMessageDialog(this, "Retiro Realizado Con Exito");
                }
                if(monto<textoRetiro){
                    JOptionPane.showMessageDialog(this, "Fondos Insuficientes");
                }
            }
            if(ProyectoCajero.Sesion==4){
                int monto=ProyectoCajero.cli4.getMonto();
                if(monto>textoRetiro){
                ProyectoCajero.cli4.setMonto(monto-textoRetiro);
                JOptionPane.showMessageDialog(this, "Retiro Realizado Con Exito");
                }
                if(monto<textoRetiro){
                    JOptionPane.showMessageDialog(this, "Fondos Insuficientes");
                }
            }
            if(ProyectoCajero.Sesion==5){
                int monto=ProyectoCajero.cli5.getMonto();
                if(monto>textoRetiro){
                ProyectoCajero.cli5.setMonto(monto-textoRetiro);
                JOptionPane.showMessageDialog(this, "Retiro Realizado Con Exito");
                }
                if(monto<textoRetiro){
                    JOptionPane.showMessageDialog(this, "Fondos Insuficientes");
                }
            }
            
            
            
            MenuPrincipal newframe = new MenuPrincipal(); //Llamar a MenuPrincipal
            newframe.setVisible(true);//Linea que ya la abre

            this.dispose();//este metodo sirve para cerrar la otra ventana

            //pueden copiar y pegar si quieren//
        }
        if (i==2){//este if es para cuando se elije no
            MenuPrincipal newframe = new MenuPrincipal(); //Llamar a MenuPrincipal
            newframe.setVisible(true);//Linea que ya la abre

            this.dispose();//este metodo sirve para cerrar la otra ventana

            //pueden copiar y pegar si quieren//
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuPrincipal newframe = new MenuPrincipal(); //Llamar a MenuPrincipal
        newframe.setVisible(true);//Linea que ya la abre

        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
